CREATE SCHEMA Application

CREATE TABLE Application.Lunch(
	Id INT IDENTITY(1,1),
	LunchID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Description VARCHAR(MAX) NOT NULL,
	Ingredients VARCHAR(MAX) NOT NULL,
	Image VARCHAR (MAX) NOT NULL
)